services:
    ErdnaxelaWeb\IbexaDesignIntegration\Showroom\ComponentFinder:
        decorates: ErdnaxelaWeb\StaticFakeDesign\Showroom\ComponentFinder
        parent: ErdnaxelaWeb\StaticFakeDesign\Showroom\ComponentFinder
        arguments:
            $designList: '%ibexa.design.list%'
            $templatePathsMap: '%ibexa.design.templates.path_map%'
        calls:
            - ['setConfigResolver', ['@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface']]
