services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\TaxonomyEntryTransformer:

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\TaxonomyEntryAssignementFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ibexa_taxonomy_entry_assignment' }

    ErdnaxelaWeb\IbexaDesignIntegration\Transformer\FieldValue\TaxonomyEntryFieldValueTransformer:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.transformer.field_value', type: 'ibexa_taxonomy_entry' }

    ErdnaxelaWeb\IbexaDesignIntegration\Pager\Filter\Handler\TaxonomyFieldFilterHandler:
        lazy: true
        tags:
            - { name: 'erdnaxelaweb.ibexa_design_integration.pager.filter_handler', type: 'taxonomy_field' }
